org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.workers.max=4

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.248
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=player_locator_plus
mod_name=Player Locator Plus NeoForge
mod_license=GPL-3.0-or-later
mod_version=2.5.1
mod_group_id=sh.sit.plp
archives_base_name=player-locator-plus-neoforged-1.21.1
mod_authors=Kanoyo, sit <me@sit.sh>
mod_description=Shows the direction of other players on a configurable HUD above the experience bar.
